# Homework

1. Complete the Python implementation of the backpropagation exercise in the **Backpropagation** section here above (cell `# try it in Python as homework!`)
    - Create the calculations for obtaining $y$ in PyTorch **using only PyTorch methods and routines**
    - Calculate the gradient
    - Check the values of the gradients and see if it is correct w.r.t. the manual calculations
2. Given the multilayer perceptron defined during the exercises from lab 1:
    - Create 10 random datapoints (with any function you wish, it can be `rand`, `randn`...) and feed them into the network
    - Given the output, calculate the Cross-Entropy loss with respect to the ground truth $[1,2,3,4,1,2,3,4,1,2]$ (classes from 1 to 4). Cross-Entropy loss:
        
        $$ CE(\mathbf{y}, \hat{\mathbf{y}}) = - \sum_{i=1}^{10} \hat{y}_i \log(y_i)$$
        
        where $y_i$ is the one-hot encoding of the $i$-th datapoint. For instance, $y_1 = [1,0,0,0]$.
        **_Note: there is an extremely handy PyTorch function for getting a one-hot encoding out of a vector, so don't try anything fancy._**
    - Backpropagate the error along the network and inspect the gradient of the parameters connecting the input layer and the first hidden layer.
3. Execute the python script `utils/randomized_backpropagation_formula.py`. This creates a formula $f(\mathbf{x})$ with randomized operators and values. Create the computational graph from this formula, do (by hand) the forward pass, then calculate (by hand) $\nabla f(\mathbf{x})$ using the backward gradient computation. Do the same calculation on PyTorch to check the correctness of your calculations. _Note: The formula created by this script is linked to your name and surname, which you have to input before_. The solution to this exercise _should_ be submitted as a scan/good quality picture of a piece of paper (or you can do it on a touch screen and submit the image...), but other formats are acceptable as well.

In [26]:
import torch

## Exercise 1

**Backpropagation**

Let us suppose we have the following calculation

$\mathbf{x} = [1,~2,~-1,~3,~5]$

$ y = f(\mathbf{x}) = \log\{[\exp (x_1 * x_2 )]^2 + \sin (x_3 + x_4 + x_5) \cdot x_5\}$

Find

$\nabla f(\mathbf{x})$

### Part 1

In [27]:
x1 = torch.tensor([1.0], requires_grad=True)
x2 = torch.tensor([2.0], requires_grad=True)
x3 = torch.tensor([-1.0], requires_grad=True)
x4 = torch.tensor([3.0], requires_grad=True)
x5 = torch.tensor([5.0], requires_grad=True)

print(x1)
print(x2)
print(x3)
print(x4)
print(x5)

# x = torch.tensor([1,2,-1,3,5], dtype=torch.float32, requires_grad=True)
# print(x)

tensor([1.], requires_grad=True)
tensor([2.], requires_grad=True)
tensor([-1.], requires_grad=True)
tensor([3.], requires_grad=True)
tensor([5.], requires_grad=True)


In [30]:
a = torch.matmul(x1, x2)
print(a)
b = x3 + x4 + x5
print(b)
c = a.exp()
print(c)
d = torch.pow(c, 2)
print(d)
g = b.sin()
print(g)
h = torch.matmul(g, x5)
print(h)
i = d + h
print(i)
y = torch.log(i)
print("\n")
print("The value of function f(x) evaluated in x is:")
print(y)

tensor(2., grad_fn=<DotBackward0>)
tensor([7.], grad_fn=<AddBackward0>)
tensor(7.3891, grad_fn=<ExpBackward0>)
tensor(54.5982, grad_fn=<PowBackward0>)
tensor([0.6570], grad_fn=<SinBackward0>)
tensor(3.2849, grad_fn=<DotBackward0>)
tensor(57.8831, grad_fn=<AddBackward0>)


The value of function f(x) evalkuated in x is:
tensor(4.0584, grad_fn=<LogBackward0>)


### Part 2

In [31]:
y.backward()
print(x1.grad)
print(x2.grad)
print(x3.grad)
print(x4.grad)
print(x5.grad)

tensor([3.7730])
tensor([1.8865])
tensor([0.0651])
tensor([0.0651])
tensor([0.0765])


### Part 3

From manual calculations performed in class, we expected:

- $\partial f/\partial x_1 = 4.14$
- $\partial f/\partial x_2 = 2.07$
- $\partial f/\partial x_3 = 0.08$
- $\partial f/\partial x_4 = 0.08$
- $\partial f/\partial x_4 = 0.093$

As you can see from previous cell in Part 2, the manual calculations are slightly different since we made use of approximations in class.

## Exercise 2

This was the artificial network built in the first assignement:

In [35]:
class MLP(torch.nn.Module):
    def __init__(self, my_bias=False):
        super().__init__()
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(5, 11, bias=my_bias),
            torch.nn.ReLU(),
            torch.nn.Linear(11, 16, bias=my_bias),
            torch.nn.ReLU(),
            torch.nn.Linear(16, 13, bias=my_bias),
            torch.nn.ReLU(),
            torch.nn.Linear(13, 8, bias=my_bias),
            torch.nn.ReLU(),
            torch.nn.Linear(8, 4, bias=my_bias),
            torch.nn.Softmax(dim=1)
        )

    def forward(self, X):
        return self.layers(X)

The following is an instance of it:

In [36]:
model = MLP()
model

MLP(
  (layers): Sequential(
    (0): Linear(in_features=5, out_features=11, bias=False)
    (1): ReLU()
    (2): Linear(in_features=11, out_features=16, bias=False)
    (3): ReLU()
    (4): Linear(in_features=16, out_features=13, bias=False)
    (5): ReLU()
    (6): Linear(in_features=13, out_features=8, bias=False)
    (7): ReLU()
    (8): Linear(in_features=8, out_features=4, bias=False)
    (9): Softmax(dim=1)
  )
)

### Part 1

Feed 10 datapoints to the network:

In [37]:
X = torch.randn(10, 5) #Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1
print(X)
print("\n")
conf_y_hat = model(X)
print(conf_y_hat)

tensor([[-0.7291, -0.5698,  1.9403, -1.6810,  0.2411],
        [ 0.0705, -0.6490,  1.1611,  0.8965, -1.1248],
        [-0.7839,  0.7453, -0.1454,  0.0465,  0.1366],
        [ 0.1248,  0.0842, -0.2018, -0.3602,  1.1874],
        [ 0.4999, -0.1815, -0.1066, -1.7452, -0.0511],
        [ 0.8780,  0.8388,  0.6155,  2.5522, -1.6753],
        [-2.5104,  0.3058, -1.6485,  0.5160, -0.2190],
        [ 0.1298, -0.8935,  0.2552,  0.1859,  0.0697],
        [ 0.5437, -1.6091,  0.2296, -0.6091,  0.0412],
        [ 0.5275, -1.6586, -1.5570, -0.2524, -1.4706]])


tensor([[0.2505, 0.2488, 0.2509, 0.2497],
        [0.2494, 0.2488, 0.2523, 0.2495],
        [0.2504, 0.2499, 0.2501, 0.2497],
        [0.2508, 0.2491, 0.2509, 0.2492],
        [0.2478, 0.2490, 0.2527, 0.2505],
        [0.2488, 0.2494, 0.2522, 0.2496],
        [0.2481, 0.2502, 0.2519, 0.2498],
        [0.2485, 0.2505, 0.2509, 0.2502],
        [0.2475, 0.2494, 0.2531, 0.2500],
        [0.2455, 0.2510, 0.2537, 0.2498]], grad_fn=<SoftmaxBackward0>

### Part 2

The predicted classes for the 10 points are then:

In [39]:
y_hat = torch.argmax(conf_y_hat, dim=1) + 1 # in order to be confrontable with the ground_truth we add 1 
y_hat

tensor([3, 3, 1, 3, 3, 3, 3, 3, 3, 3])

Define the ground truth:

In [61]:
# We keep it with float point since the torch.nn.functional.one_hot function doesn't allow integers
ground_truth = torch.tensor([1,2,3,4,1,2,3,4,1,2]) # dtype=torch.int) or ground_truth.int() in case
ground_truth

tensor([1, 2, 3, 4, 1, 2, 3, 4, 1, 2])

Define the Cross-Entropy Loss:
$$ CE(\mathbf{y}, \hat{\mathbf{y}}) = - \sum_{i=1}^{10} \hat{y}_i \log(y_i)$$
        
where $y_i$ is the one-hot encoding of the $i$-th datapoint. For instance, $y_1 = [1,0,0,0]$.

**_Note: there is an extremely handy PyTorch function for getting a one-hot encoding out of a vector, so don't try anything fancy._**

In [67]:
def ce_loss(y_hat, y):
    # First we need to transform y in one-hot encoding tensor of shape 4 x 10.
    # To do it we must rescale the ground_truth values in compliance with the function torch.nn.functional.one_hot,
    # since in order to work num_classes must be greater than the biggest values among ground_truth.
    scaled_truth = y-1
    # Then we apply the function one_hot (if num_classes=-1 then num_classes=max_value in ground_truth + 1)
    y_hot = torch.nn.functional.one_hot(scaled_truth, num_classes=-1) 
    loss = (-1) * ((y_hat-1) @ y_hot.log()).sum()
    loss.int()
    return loss

Now let's evaluate it:

In [68]:
loss = ce_loss(y_hat, ground_truth)
loss

RuntimeError: expected scalar type Long but found Float

In [49]:
loss = ce_loss(y_hat, ground_truth)
loss

RuntimeError: one_hot is only applicable to index tensor.

## Exercise 3

Input your name, then press ENTER: Valeria Insogna

f(X) =  exp((sin(x1 + x2) / ReLU(x3 + x4)) - x5)

Your values
{'x1': 3, 'x2': 4, 'x3': -2, 'x4': -1, 'x5': -2}

Calculate ∇f(X) [NB: if division by 0, change the value(s) of X responsible for that]

In [32]:
x_1 = torch.tensor([3.0], requires_grad=True)
x_2 = torch.tensor([4.0], requires_grad=True)
x_3 = torch.tensor([2.0], requires_grad=True) #I have change it from -2 to +2 otherwise there is a  division with denominator 0! 
x_4 = torch.tensor([-1.0], requires_grad=True)
x_5 = torch.tensor([-2.0], requires_grad=True)

print(x_1)
print(x_2)
print(x_3)
print(x_4)
print(x_5)

tensor([3.], requires_grad=True)
tensor([4.], requires_grad=True)
tensor([2.], requires_grad=True)
tensor([-1.], requires_grad=True)
tensor([-2.], requires_grad=True)


Let's first evaluate the forward function step by step:

In [33]:
a = x_1 + x_2
print(a)
b = x_3 + x_4
print(b)
c = a.sin()
print(c)
d = torch.nn.functional.relu(b)
print(d)
e = c/d
print(e)
f = e - x_5
print(f)
g = f.exp()
print(g)


tensor([7.], grad_fn=<AddBackward0>)
tensor([1.], grad_fn=<AddBackward0>)
tensor([0.6570], grad_fn=<SinBackward0>)
tensor([1.], grad_fn=<ReluBackward0>)
tensor([0.6570], grad_fn=<DivBackward0>)
tensor([2.6570], grad_fn=<SubBackward0>)
tensor([14.2533], grad_fn=<ExpBackward0>)


This is the image of the manual calculations for the backward propagation:

![](ex2.png)

Now let's verify the manual counts:

In [34]:
g.backward()
print(x_1.grad)
print(x_2.grad)
print(x_3.grad)
print(x_4.grad)
print(x_5.grad)

tensor([10.7456])
tensor([10.7456])
tensor([-9.3642])
tensor([-9.3642])
tensor([-14.2533])
